// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snobyrepunxiqualjlps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub2J5cmVwdW54aXF1YWxqbHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTEzNzMsImV4cCI6MjA3MDUyNzM3M30.wRKzH1UeuyLlF53H5jXTv4Y7UL1_xrhk6fNSWBEs0F4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});